baseurl = "https://zapata1.github.io/NarbaisDamienBlog/"
title = "Accueil Damien Narbais"
theme = "ghostwriter"
languageCode = "en-us"
copyright = "Damien Narbais"
disqusShortname = "XXX"
googleAnalytics = "XXX"

[Author]
    name = "Damien Narbais"
    profile = "https://google.com/+XXX"

[Taxonomies]
    tag = "tags"

[Params]
    intro = true
    headline = "Damien Narbais"
    description = "Student Engineer"
    github = "https://github.com/zapata1"
    gitlab = "https://gitlab.com/XXX"
    linkedin = "https://www.linkedin.com/in/damien-narbais-jaureguy/"
    gplus = "https://google.com/+XXX"
    twitter = "https://twitter.com/XXX"
    stackoverflow = "https://stackoverflow.com/users/XXX/YYY"
    email = "damien.narbais@gmail.com"
    opengraph = true
    shareTwitter = true
    shareFacebook = true
    shareGooglePlus = true
    shareLinkedIn = false
    dateFormat = "Mon, Jan 2, 2006"
    highlightJsUrl = ""
    highlightJsLocalUrl = ""

[Permalinks]
    post = "/:year/:month/:day/:filename/"

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Projects"
    url = "/project/"
    weight = 2

[[menu.main]]
    name = "A propos"
    url = "/page/about/"
    weight = 4
