contentDir = "content"
layoutDir = "layouts"
publishDir = "docs"
buildDrafts = false
canonifyURLs = true
baseurl = "https://zapata1.github.io/NarbaisDamienBlog/"
languageCode = "en-us"
title = "Narbais Blog"
# theme
theme = "minimal"
# Comment the themesDir option if you use this theme in production
# themesDir = "../.."
# google analytics
GoogleAnalytics = "UA-XXXXXX"
# sectionPagesMenu = "main"


[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/post/"
    name = "Posts"
    weight = 2

[[menu.main]]
    url = "/project/"
    name = "Projects"
    weight = 3

[[menu.main]]
    url = "/About/"
    name = "About"
    weight = 4


[taxonomies]
  category = "categories"
  tag = "tags"

[params]
  description = "Etudiant en 4ème année d'école d'ingénieur"
  author = "Damien Narbais"
  lieu = "Lille"
  keywords = ["hugo-now", "hugo"]
  avatar = "/img/photo_CV.png"
  displayauthor = false
  # pygments
  PygmentsUseClasses = true
  PygmentsCodeFences = true
  # pagination
  paginate = 10
  paginatePath = "page"
  currently = "Bienvenue sur mon chantier encore en construction !"
  githubUsername = "zapata1"
  accent = "brown"
  showBorder = true
  backgroundColor = "white"
  font = "Roboto Condensed" # should match the name on Google Fonts!
  highlight = true
  highlightStyle = "solarized-dark"
  highlightLanguages = ["BigData", "java", "C", "python", "NoSQL", "TensorFlow"]
