baseurl = "https://zapata1.github.io/NarbaisDamienBlog/docs/"
languageCode = "en-us"
title = "Narbais Blog"
# theme
theme = "ghostwriter"
# Comment the themesDir option if you use this theme in production
# themesDir = "../.."
# google analytics
GoogleAnalytics = "UA-XXXXXX"
sectionPagesMenu = "main"


[[menu.essential]]
    name = "Accueil"
    pre = "<i class='fa fa-road'></i>"
    weight = -100
    url = "/Accueil/"
[[menu.essential]]
    name = "Comment faire ?"
    pre = "<i class='fa fa-road'></i>"
    weight = -90
    url = "/domaine-intervention/"
[[menu.essential]]
    name = "Projets"
    pre = "<i class='fa fa-road'></i>"
    weight = -80
    url = "/projets/"
[[menu.essential]]
    name = "Contact"
    pre = "<i class='fa fa-road'></i>"
    weight = -70
    url = "/contact/"


[taxonomies]
  category = "categories"
  tag = "tags"

[params]
  description = "Etudiant en 4ème année d'école d'ingénieur"
  author = "Damien Narbais"
  lieu = "Lille"
  keywords = ["hugo-now", "hugo"]
  avatar = "/img/photo_CV.png"
  displayauthor = false
  # pygments
  PygmentsUseClasses = true
  PygmentsCodeFences = true
  # pagination
  paginate = 10
  paginatePath = "page"
